### ISSUE TITLE
neon not being used on aarch64

### ISSUE THREAD

**Issue by shakesoda** [scoopr/vectorial#11]
`__ARM_NEON__` is apparently legacy, and building with clang for arm64 i need to change config.h:15 to also check for  `__ARM_NEON` for `VECTORIAL_NEON` to be set.

**Comment by scoopr** [comment]
Oh, interesting! Well that should be trivial to fix, do you want to make a PR since you have a place to test it? Which platform is this on?

**Comment by shakesoda** [comment]
@scoopr sure thing, made the PR. this is with android (building for oculus quest, latest NDK i think), and seems to be the specified behavior for aarch64.
